[package]
name = "td_exercices_choisis"
version = "0.1.0"
authors = ["Pablo Oliveira <pablo.oliveira@uvsq.fr>, St√©phane Lopes <stephane.lopes@uvsq.fr>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
